from fpdf import FPDF
import csv

class PDFReport(FPDF):
    def header(self):
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, "IS 456 Slab Design Report", ln=True, align="C")
        self.ln(5)
    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by IS 456 Slab Designer", align="C")

def export_pdf(result_dict, filename="slab_design_report.pdf"):
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Design Summary", ln=True)
    pdf.set_font("Arial", size=11)
    for key, value in result_dict.items():
        if key == "warnings" or key == "detailed_steps":
            continue
        # convert to printable string safely
        pdf.multi_cell(0, 7, f"{key}: {value}")
    # warnings
    pdf.ln(4)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Warnings:", ln=True)
    pdf.set_font("Arial", size=11)
    if result_dict.get("warnings"):
        for w in result_dict["warnings"]:
            pdf.multi_cell(0, 7, f"- {w}")
    else:
        pdf.cell(0, 7, "No warnings.", ln=True)
    # detailed steps
    if result_dict.get("detailed_steps"):
        pdf.add_page()
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Detailed Calculation Steps", ln=True)
        pdf.set_font("Courier", size=9)
        for step in result_dict["detailed_steps"]:
            pdf.multi_cell(0, 6, step.get("title", ""))
            pdf.multi_cell(0, 6, step.get("body", ""))
            pdf.ln(2)
    pdf.output(filename)
    return filename

def export_csv(result_dict, filename="slab_design_results.csv"):
    with open(filename, mode="w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Parameter", "Value"])
        for key, value in result_dict.items():
            if key == "detailed_steps":
                continue
            if key == "warnings" and value:
                writer.writerow([])
                writer.writerow(["Warnings", ""])
                for w in value:
                    writer.writerow(["", w])
                continue
            writer.writerow([key, value])
    return filename
